name: Claude Code Assistant
on:
  issue_comment:
    types: [created]

jobs:
  claude-assistant:
    if: >
      github.event.issue.user.login == 'watany-dev' &&
      contains(github.event.comment.body, '@cli-claude')
    runs-on: ubuntu-latest
    env:
      # for Amazon Bedrock
      CLAUDE_CODE_USE_BEDROCK: 1
      ANTHROPIC_MODEL: us.anthropic.claude-sonnet-4-20250514-v1:0
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
env:
      # for Amazon Bedrock
      CLAUDE_CODE_USE_BEDROCK: 1
      ANTHROPIC_MODEL: us.anthropic.claude-sonnet-4-20250514-v1:0
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
      # for Git Hub MCP Server
      GITHUB_DYNAMIC_TOOLSETS: 1
      GITHUB_TOOLSETS: "all"
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      checks: read
      issues: readSelection deleted

      security-events: read
      statuses: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GitHubActions${{ github.run_id }}
          mask-aws-account-id: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install Claude CLI
        run: |
          npm install -g @anthropic-ai/claude-code --force --no-os-check
          claude --version
          claude config set hasTrustDialogAccepted true          
      - name: Process Comment with Claude
        run: |
          CLAUDE_PROMPT="${{ github.event.comment.body }}"

          if [ -z "$CLAUDE_PROMPT" ]; then
            CLAUDE_PROMPT="Please help me with this issue or pull request."
          fi

          echo "$CLAUDE_PROMPT" | claude \
            --allowedTools "mcp__GitHub__add_pull_request_review_comment,mcp__GitHub__create_pull_request_review,mcp__GitHub__enable_toolset,mcp__GitHub__get_pull_request,mcp__GitHub__get_pull_request_files,mcp__GitHub__get_pull_request_status,mcp__GitHub__get_pull_request_reviews,mcp__GitHub__get_pull_request_comments,mcp__GitHub__get_toolset_tools,mcp__GitHub__list_available_toolsets,mcp__GitHub__list_pull_requests,Bash,Read,Write,Edit,Create,gh" \
            --mcp-debug \
            --mcp-config .mcp.json \
            --print --output-format json | tee output.json
          cat output.json |  jq -r '.result' > response.txt
          echo "" >> response.txt
          cat output.json |  jq -r '.total_cost' >> response.txt
     
      - name: Post the response as a comment
        run: |
          if [ ! -s response.txt ]; then
            echo "⚠️ Claude の result が空なのでスキップします。"
            exit 0
          fi

          # --body-file でファイル丸ごと渡す
          gh issue comment ${{ github.event.issue.number }} --body-file response.txt
