name: Claude Assistant
on:
  issue_comment:
    types: [created]

jobs:
  claude-assistant:
    if: >
      github.event.issue.user.login == 'watany-dev' &&
      contains(github.event.comment.body, '@cli-claude')
    runs-on: ubuntu-latest
    env:
      CLAUDE_CODE_USE_BEDROCK: 1
      ANTHROPIC_MODEL: us.anthropic.claude-sonnet-4-20250514-v1:0
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: read
      pull-requests: read
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GitHubActions${{ github.run_id }}
          mask-aws-account-id: true

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install Claude CLI
        run: |
          npm install -g @anthropic-ai/claude-code --force --no-os-check
          claude config set hasTrustDialogAccepted true
          # …（省略）…

      - name: Process Comment with Claude
        run: |
          FULL_BODY="${{ github.event.comment.body }}"
          CLAUDE_PROMPT=$(echo "$FULL_BODY" | sed -E 's/.*@cli-claude[[:space:]]*//')
          [ -z "$CLAUDE_PROMPT" ] && CLAUDE_PROMPT="Please help me with this issue or pull request."

          claude \
            --allowedTools "mcp__GitHub__add_pull_request_review_comment,..." \
            --prompt "$CLAUDE_PROMPT" \
            --print \
            --output-format json \
          | tee output.json

      - name: Post the response as a comment
        run: |
          RESPONSE=$(jq -r '.completions[0].data.content // empty' output.json)
          if [ -z "$RESPONSE" ]; then
            echo "⚠️ Claude の出力が空なのでスキップ。"
            exit 0
          fi
          gh issue comment ${{ github.event.issue.number }} --body "$RESPONSE"
